spring:
  profiles.active: default
---
spring:
  profiles: default
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
---
spring:
  profiles: windowsProfile
  data:
    mongodb:
      host: 192.168.99.100
